<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticIniteb47a61547a5bac31857fac99d15d00e
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MessageBird\\' => 12,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MessageBird\\' => 
        array (
            0 => __DIR__ . '/..' . '/messagebird/php-rest-api/src/MessageBird',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticIniteb47a61547a5bac31857fac99d15d00e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticIniteb47a61547a5bac31857fac99d15d00e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticIniteb47a61547a5bac31857fac99d15d00e::$classMap;

        }, null, ClassLoader::class);
    }
}
